export enum SynthTypeKeys {
  ADD_OSCILLATOR = 'ADD_OSCILLATOR',
  REMOVE_OSCILLATOR = 'REMOVE_OSCILLATOR',
  ADD_PRESSED_KEY = 'ADD_PRESSED_KEY',
  REMOVE_PRESSED_KEY = 'REMOVE_PRESSED_KEY',
  REMOVE_ALL_KEYS = 'REMOVE_ALL_KEYS',
}

export enum OtherTypeKeys {
  OTHER_ACTION = 'something_else',
}
